name: MessagePlugin
version: 1.0
main: me.earth.messageplugin.MessagePlugin
authors: [Ea_r_th]
description: My sample plugin for a messaging system

commands:
  addressEnvelope:
    description: Addresses an envelope.
  giveEnvelope:
    description: gives the player an envelope
